#!/bin/sh
set -e

echo "==> Starting Drupal container..."

# Wait for database to be ready
echo "==> Waiting for database connection..."
MAX_TRIES=30
TRIES=0
until mysql --skip-ssl -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" -e "SELECT 1" "$DB_NAME" > /dev/null 2>&1; do
    TRIES=$((TRIES + 1))
    if [ $TRIES -ge $MAX_TRIES ]; then
        echo "Error: Could not connect to database after $MAX_TRIES attempts"
        exit 1
    fi
    echo "Database not ready yet... (attempt $TRIES/$MAX_TRIES)"
    sleep 2
done
echo "==> Database is ready!"

# Navigate to Drupal root
cd /var/www/html

# Setup settings.php if it doesn't exist or doesn't have database config
SETTINGS_FILE="/var/www/html/sites/default/settings.php"
if [ ! -f "$SETTINGS_FILE" ] || ! grep -q '\$databases\[.default.\]\[.default.\]' "$SETTINGS_FILE" 2>/dev/null; then
    echo "==> Setting up settings.php..."

    # Copy default settings if settings.php doesn't exist
    if [ ! -f "$SETTINGS_FILE" ]; then
        cp /var/www/html/sites/default/default.settings.php "$SETTINGS_FILE"
    fi

    # Append database configuration
    cat >> "$SETTINGS_FILE" << EOF

/**
 * Database configuration (auto-generated by entrypoint.sh)
 */
\$databases['default']['default'] = [
  'database' => '${DB_NAME}',
  'username' => '${DB_USER}',
  'password' => '${DB_PASSWORD}',
  'host' => '${DB_HOST}',
  'port' => '${DB_PORT}',
  'driver' => 'mysql',
  'prefix' => '',
  'collation' => 'utf8mb4_general_ci',
];

/**
 * Hash salt (auto-generated by entrypoint.sh)
 */
\$settings['hash_salt'] = '${DRUPAL_HASH_SALT}';

/**
 * Trusted host patterns
 */
\$settings['trusted_host_patterns'] = [
  '${DRUPAL_TRUSTED_HOST}',
  '^localhost\$',
];

/**
 * Config sync directory
 */
\$settings['config_sync_directory'] = '../config/sync';

/**
 * File paths
 */
\$settings['file_private_path'] = 'sites/default/files/private';

/**
 * Production settings
 */
\$settings['container_yamls'][] = \$app_root . '/' . \$site_path . '/services.yml';

EOF

    # Set proper permissions
    chmod 444 "$SETTINGS_FILE"
    echo "==> settings.php configured!"
fi

# Ensure files directory has correct permissions
echo "==> Setting file permissions..."
chown -R www-data:www-data /var/www/html/sites/default/files
chmod -R 755 /var/www/html/sites/default/files

# Run Drupal updates if database is initialized
echo "==> Checking if Drupal is installed..."
if drush status bootstrap 2>/dev/null | grep -q "Successful"; then
    echo "==> Running database updates..."
    drush updatedb -y --no-interaction || true

    echo "==> Importing configuration..."
    drush config:import -y --no-interaction || true

    echo "==> Clearing cache..."
    drush cache:rebuild -y --no-interaction || true

    echo "==> Drupal updates complete!"
else
    echo "==> Drupal not yet installed. Please import your database."
fi

echo "==> Starting nginx and PHP-FPM via supervisord..."
exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
