<?php

/**
 * @file
 * Contains skuhan_global.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Markup;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function skuhan_global_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the skuhan_global module.
    case 'help.page.skuhan_global':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Skuhan.com Global module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function skuhan_global_theme() {
  return [
    'skuhan_global' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function skuhan_global_preprocess_menu(&$variables) {
  if(isset($variables['menu_name']) && $variables['menu_name'] == 'skuhan-main-menu') {
    foreach ($variables['items'] as &$item) {
      $item['title'] = Markup::create('<span>' . $item['title'] . '</span>');
    }
  }
}
